### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by fabioimpe** [chunkai1312/muibox#15]
Hello,
I just noticed the deprecation warnings below since I started using muibox.

`Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.`

After some investigation I figured out that this is caused by "recompose" package.
Since that package is used just to manage a state on the prompt dialog, is it possible to get rid of it and manage the state with the useState hook?

**Comment by cargallo** [comment]
is there any possibility to improve the code to avoid having this warning? It's really anoying

**Comment by chunkai1312** [comment]
I've published v1.5.0 to remove recompose dependency. Thanks!
