### ISSUE TITLE
Will muibox support react 18?

### ISSUE THREAD

**Issue by samislam** [chunkai1312/muibox#18]
When installing muibox while using React 18, the following errors show up:

![Loading...](https://i.ibb.co/Qn8GMT7/Screenshot-from-2022-08-05-11-14-06.png)

Will muibox support react 18?

**Comment by pablorobert** [comment]
Hi, I made a PR updating these old deps. Awaing to be merged.

I accomplished updating storybook as well but it's not in PR.

Later i'm gonna try update material ui to v6 as well.

**Comment by chunkai1312** [comment]
@pablorobert Sorry for the late reply, and thank you for your PR! I’ve just merged it. If you have any further updates, please feel free to send another PR. Thanks again!

**Comment by chunkai1312** [comment]
@pablorobert The new version has been released! If you encounter any issues or need assistance, please let me know. Thanks again for your help!
