### ISSUE TITLE
Broken v3.0.0

### ISSUE THREAD

**Issue by pablorobert** [chunkai1312/muibox#21]
Sorry cause I think I broke v3.0.0.

Some plugin inserted 'file' in muibox dependency for God know the reason.

Anyway i think now is good to go.

Accomplished to use 'pure' npm as well cause it was not working before (only with pnpm or bun)

I took the liberty to set version 3.0.1

**Comment by pablorobert** [comment]
By the way, if you could please run build-storybook cause I added one more story for Prompt.
Thanks

**Comment by chunkai1312** [comment]
@pablorobert Thank you for the fix! I’ll review it shortly, and release it as soon as possible.

**Comment by chunkai1312** [comment]
@pablorobert Version 3.0.1 has been released, and the storybook has been updated accordingly. Thanks again!
